<?php
$html = "";
$html .= "<!DOCTYPE html>";
$html .= "\n<html>";
$html .= "\n\t<head>";
$html .= "\n\t\t<meta charset=\"utf-8\" />";
$html .= "\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
$html .= "\n\t\t<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\" />";
$html .= "\n\t\t<link rel=\"stylesheet\" href=\"../css/style.css\" />";
$html .= "\n\t\t<link rel=\"stylesheet\" href=\"../css/jquery-ui.css\" type=\"text/css\" media=\"screen\" title=\"default\" />";
$html .= "\n\t\t<link rel=\"stylesheet\" href=\"../css/bootstrap-theme.min.css\">";
$html .= "\n\t\t<script type=\"text/javascript\" language=\"javascript\" src=\"../js/md5.pack.js\"></script>";
$html .= "\n\t\t<script type=\"text/javascript\" language=\"javascript\" src=\"../js/jquery.min.js\"></script>";
$html .= "\n\t\t<script type=\"text/javascript\" language=\"javascript\" src=\"../js/jquery-1.10.2.js\"></script>";
$html .= "\n\t\t<title>Respuesta</title>";
$html .= "\n\t</head>";
$html .= "\n\t<body>";
$html .= "\n\t\t<div class=\"modal fade\" id=\"myModal1\" role=\"dialog\" align=\"center\" >";
$html .= "\n\t\t\t<div class=\"modal-dialog\">";
$html .= "\n\t\t\t\t<div class=\"modal-content\">";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-header\">";
$html .= "\n\t\t\t\t\t\t<h4 class=\"modal-title\" style=\"font-size: 24px; padding: 3px;\">Información</h4>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div class=\"modal-body\" style=\"margin-top: 8px\">";
$html .= "\n\t\t\t\t\t\t<p> Información guardada correctamente.</p>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-footer\">";
$html .= "\n\t\t\t\t\t\t<button type=\"button\" id=\"btnA\" class=\"btn btn-default\" style=\"color: #000; margin-top: 2px\" data-dismiss=\"modal\" >Aceptar</button>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t</div>";
$html .= "\n\t\t\t</div>";
$html .= "\n\t\t</div>";
$html .= "\n\t\t<div class=\"modal fade\" id=\"myModal2\" role=\"dialog\" align=\"center\" >";
$html .= "\n\t\t\t<div class=\"modal-dialog\">";
$html .= "\n\t\t\t\t<div class=\"modal-content\">";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-header\">";
$html .= "\n\t\t\t\t\t\t<h4 class=\"modal-title\" style=\"font-size: 24; padding: 3px;\">Información</h4>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div class=\"modal-body\" style=\"margin-top: 8px\">";
$html .= "\n\t\t\t\t\t\t<p>No se pudo guardar la información.</p>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-footer\">";
$html .= "\n\t\t\t\t\t\t<button type=\"button\" id=\"btnA2\" class=\"btn btn-default\" data-dismiss=\"modal\" >Aceptar</button>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t</div>";
$html .= "\n\t\t\t</div>";
$html .= "\n\t\t</div>";
$html .= "\n\t\t<div class=\"modal fade\" id=\"myModal3\" role=\"dialog\" align=\"center\" >";
$html .= "\n\t\t\t<div class=\"modal-dialog\">";
$html .= "\n\t\t\t\t<div class=\"modal-content\">";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-header\">";
$html .= "\n\t\t\t\t\t\t<h4 class=\"modal-title\" style=\"font-size: 24; padding: 3px;\">Información</h4>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div class=\"modal-body\" style=\"margin-top: 8px\">";
$html .= "\n\t\t\t\t\t\t<p>Información modificada correctamente.</p>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-footer\">";
$html .= "\n\t\t\t\t\t\t<button type=\"button\" id=\"btnA3\" class=\"btn btn-default\" data-dismiss=\"modal\" >Aceptar</button>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t</div>";
$html .= "\n\t\t\t</div>";
$html .= "\n\t\t</div>";
$html .= "\n\t\t<div class=\"modal fade\" id=\"myModal4\" role=\"dialog\" align=\"center\" >";
$html .= "\n\t\t\t<div class=\"modal-dialog\">";
$html .= "\n\t\t\t\t<div class=\"modal-content\">";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-header\">";
$html .= "\n\t\t\t\t\t\t<h4 class=\"modal-title\" style=\"font-size: 24; padding: 3px;\">Información</h4>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div class=\"modal-body\" style=\"margin-top: 8px\">";
$html .= "\n\t\t\t\t\t\t<p>No se pudo modificar la información.</p>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-footer\">";
$html .= "\n\t\t\t\t\t\t<button type=\"button\" id=\"btnA4\" class=\"btn btn-default\" data-dismiss=\"modal\" >Aceptar</button>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t</div>";
$html .= "\n\t\t\t</div>";
$html .= "\n\t\t</div>";
$html .= "\n\t\t<div class=\"modal fade\" id=\"myModal5\" role=\"dialog\" align=\"center\" >";
$html .= "\n\t\t\t<div class=\"modal-dialog\">";
$html .= "\n\t\t\t\t<div class=\"modal-content\">";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-header\">";
$html .= "\n\t\t\t\t\t\t<h4 class=\"modal-title\" style=\"font-size: 24; padding: 3px;\">Información</h4>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div class=\"modal-body\" style=\"margin-top: 8px\">";
$html .= "\n\t\t\t\t\t\t<p>Información eliminada correctamente.</p>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-footer\">";
$html .= "\n\t\t\t\t\t\t<button type=\"button\" id=\"btnA5\" class=\"btn btn-default\" data-dismiss=\"modal\" >Aceptar</button>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t</div>";
$html .= "\n\t\t\t</div>";
$html .= "\n\t\t</div>";
$html .= "\n\t\t<div class=\"modal fade\" id=\"myModal6\" role=\"dialog\" align=\"center\" >";
$html .= "\n\t\t\t<div class=\"modal-dialog\">";
$html .= "\n\t\t\t\t<div class=\"modal-content\">";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-header\">";
$html .= "\n\t\t\t\t\t\t<h4 class=\"modal-title\" style=\"font-size: 24; padding: 3px;\">Información</h4>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div class=\"modal-body\" style=\"margin-top: 8px\">";
$html .= "\n\t\t\t\t\t\t<p>No se pudo eliminar la información, el registo seleccionado está siendo utilizado por otra dependencia.</p>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t\t<div id=\"forma-modal\" class=\"modal-footer\">";
$html .= "\n\t\t\t\t\t\t<button type=\"button\" id=\"btnA6\" class=\"btn btn-default\" data-dismiss=\"modal\" >Aceptar</button>";
$html .= "\n\t\t\t\t\t</div>";
$html .= "\n\t\t\t\t</div>";
$html .= "\n\t\t\t</div>";
$html .= "\n\t\t</div>";
$html .= "\n\t</body>";
$html .= "\n\t<script src=\"../js/bootstrap.min.js\"></script>";
$html .= "\n\t<script>";
switch ($_REQUEST['action']) {
    case 'registrado':
        $html .= "\n\t\t$(\"#myModal1\").modal({backdrop: 'static', keyboard: false});";
        $html .= "\n\t\t$(\"#btnA\").click(function(){";
        $html .= "\n\t\t\twindow.location='../CargarAlmacen.php';";
        $html .= "\n\t\t});";
        break;

    case 'noregistrado':
        $html .= "\n\t\t$(\"#myModal2\").modal({backdrop: 'static', keyboard: false});";
        $html .= "\n\t\t$(\"#btnA2\").click(function(){";
        $html .= "\n\t\t\twindow.location='../CargarAlmacen.php';";
        $html .= "\n\t\t});";
        break;

    case 'modificado':
        $html .= "\n\t\t$(\"#myModal3\").modal({backdrop: 'static', keyboard: false});";
        $html .= "\n\t\t$(\"#btnA3\").click(function(){";
        $html .= "\n\t\t\twindow.location='../CargarAlmacen.php';";
        $html .= "\n\t\t});";
        break;

    case 'nomodificado':
        $html .= "\n\t\t$(\"#myModal4\").modal({backdrop: 'static', keyboard: false});";
        $html .= "\n\t\t$(\"#btnA4\").click(function(){";
        $html .= "\n\t\t\twindow.location='../CargarAlmacen.php';";
        $html .= "\n\t\t});";
        break;

    case 'eliminado':
        $html .= "\n\t\t$(\"#myModal5\").modal({backdrop: 'static', keyboard: false});";
        $html .= "\n\t\t$(\"#btnA5\").click(function(){";
        $html .= "\n\t\t\twindow.location='../CargarAlmacen.php';";
        $html .= "\n\t\t});";
        break;

    case 'noeliminado':
        $html .= "\n\t\t$(\"#myModal6\").modal({backdrop: 'static', keyboard: false});";
        $html .= "\n\t\t$(\"#btnA6\").click(function(){";
        $html .= "\n\t\t\twindow.location='../CargarAlmacen.php';";
        $html .= "\n\t\t});";
        break;
}
$html .= "\n\t</script>";
$html .= "\n</html>";
echo $html;